[metadata]
creation_date = "2021/10/07"
maturity = "production"
updated_date = "2021/10/07"

[rule]
author = ["Elastic"]
description = """
This rule detects the use of PSReflect in PowerShell scripts. Attackers leverage PSReflect as a library that enables
PowerShell to access win32 API functions.,
"""
false_positives = ["Legitimate Powershell Scripts that make use of PSReflect to access the win32 API"]
from = "now-9m"
index = ["winlogbeat-*", "logs-windows.*"]
language = "kuery"
license = "Elastic License v2"
name = "PowerShell PSReflect Script"
references = ["https://github.com/mattifestation/PSReflect/blob/master/PSReflect.psm1"]
risk_score = 47
rule_id = "56f2e9b5-4803-4e44-a0a4-a52dc79d57fe"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Execution"]
timestamp_override = "event.ingested"
type = "query"

query = '''
event.code:"4104" and 
  powershell.file.script_block_text : (
    New-InMemoryModule or
    Add-Win32Type or
    psenum or
    DefineDynamicAssembly or
    DefineDynamicModule or
    Reflection.TypeAttributes or
    Reflection.Emit.OpCodes or
    Reflection.Emit.CustomAttributeBuilder or
    Runtime.InteropServices.DllImportAttribute
  )
'''


[[rule.threat]]
framework = "MITRE ATT&CK"

[[rule.threat.technique]]
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
id = "T1059"

    [[rule.threat.technique.subtechnique]]
    name = "PowerShell"
    reference = "https://attack.mitre.org/techniques/T1059/001/"
    id = "T1059.001"

[[rule.threat.technique]]
name = "Native API"
reference = "https://attack.mitre.org/techniques/T1106/"
id = "T1106"

[rule.threat.tactic]
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
id = "TA0002"

